// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARan6D4DZZTQrMOakrBh_3ypbyDvuWZk8',
    appId: '1:363540717974:web:99f0f11401d77d6544bdb7',
    messagingSenderId: '363540717974',
    projectId: 'portfolio-cd807',
    authDomain: 'portfolio-cd807.firebaseapp.com',
    storageBucket: 'portfolio-cd807.firebasestorage.app',
    measurementId: 'G-BT7ZT88NTF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3lAfHb-dLTyUklClCDSFAl3vuHuY_AxE',
    appId: '1:363540717974:android:d5d9f68389e5218944bdb7',
    messagingSenderId: '363540717974',
    projectId: 'portfolio-cd807',
    storageBucket: 'portfolio-cd807.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZ0peBBschJhMvUCMyj3epdhRjbjuzSGk',
    appId: '1:363540717974:ios:92d2fb3e228c3d6544bdb7',
    messagingSenderId: '363540717974',
    projectId: 'portfolio-cd807',
    storageBucket: 'portfolio-cd807.firebasestorage.app',
    iosBundleId: 'shivakumar.com.portfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARan6D4DZZTQrMOakrBh_3ypbyDvuWZk8',
    appId: '1:363540717974:web:b451e74c61aa581d44bdb7',
    messagingSenderId: '363540717974',
    projectId: 'portfolio-cd807',
    authDomain: 'portfolio-cd807.firebaseapp.com',
    storageBucket: 'portfolio-cd807.firebasestorage.app',
    measurementId: 'G-5ZYJEXX56F',
  );
}
